#include <stdio.h>
#include <stdlib.h>

char* breakPalindrome (char* palindrome) {
    int count = 0;
    int index = 0;
    char *temp = NULL;

    for (index = 0; palindrome[index] != '\0'; ++index) {
        ++count;
    }
    if (count == 1) {
        // return null-terminator if there's only 1 element
        return palindrome + count;
    }
    for (index = 0; index < count / 2; ++index) {
        // find the first character that is not 'a' in palindrome
        if (temp == NULL && palindrome[index] != 'a') {
            temp = &palindrome[index];
        }
    }
    if (temp == NULL) {
        // replace the latest 'a' with 'b'
        palindrome[count - 1] = 'b';
    } else {
        // replace the character with 'a'
        *temp = 'a';
    }    

    return palindrome;
}

// This is generated by Github Copilot
int checkPalindrome (char* str) {
    int left = 0;
    int right = 0;

    for (right = 0; str[right] != '\0'; ++right);
    --right;

    while (left < right) {
        if (str[left] != str[right]) {
            return 0;
        }
        ++left;
        --right;
    }

    return 1;
}

int main (void) {
  char *palindrome;
  char *result;

  palindrome = (char *) malloc (1024 * sizeof(char));
  scanf ("%s", palindrome);

  if (checkPalindrome (palindrome) == 0) {
      printf ("Input is not a palindrome.\n");
      free (palindrome);
      return 0;
  }

  result = breakPalindrome (palindrome);
  printf ("%s\n", result);

  free (palindrome);
  return 0;
}